version: '3'
services:
  db:
    image: postgres:latest
    ports:
      - "5490:5432"
    environment:
      - POSTGRES_PASSWORD=$Password
      - POSTGRES_USER=$User
      - POSTGRES_DB=$DB
    restart: always             # run as a service
    volumes:
      - "db_data:/var/lib/postgresql/data"

volumes:
  db_data:

